### ISSUE TITLE
Version 3.0.0-Alpha.1 not detecting TCL

### ISSUE THREAD

**Issue by travischapman** [bschlenk/homebridge-roku#118]
I am using Version 3.0.0-Alpha.1
My Roku TV is the TCL 55C807

Whenever I run the homebridge-roku-config, it gets a timeout error saying no Roku devices are found in 10 seconds. 

I have confirmed that my homebridge server is running on the same network as the TV. I tried extending the timeout up to 60 seconds and that did not help either.

Is there anything I am missing?

**Comment by travischapman** [comment]
The error that prints out is:
`Error: Could not find any Roku devices after 10 seconds
    at RokuFinder.<anonymous> (/usr/local/lib/node_modules/homebridge-roku/node_modules/roku-client/dist/discover.js:95:20)
    at RokuFinder.emit (events.js:198:13)
    at Timeout.done (/usr/local/lib/node_modules/homebridge-roku/node_modules/roku-client/dist/discover.js:61:19)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)`

**Comment by ghendrickson82** [comment]
Having this same issue with a TCL 65R615

**Comment by isupremedyou** [comment]
@fullmetaljester I ended up having to hardcore the values in the homebridge `config.json` file, let me know if you need any help with that

**Comment by fullmetaljester** [comment]
i suspected that might be the case. I'm actually doing it in HOOBS too but the process is the same just via the GUI.

**Comment by hetkin** [comment]
I'm having the same problem with a TCL Roku TV. Can anyone share their config?

**Comment by isupremedyou** [comment]
@hetkin do you have Google WiFi? I ask because today I switched over to using Eero for my WiFi and I was able to get the plugin to detect my TV.

**Comment by mushbuddygoose** [comment]
> @fullmetaljester I ended up having to hardcode the values in the homebridge `config.json` file, let me know if you need any help with that

Could you share your config. I cant get my tcl to work either and not sure what i need in the config

**Comment by Jacksonbm1** [comment]
Anyone have any luck on this?
