### ISSUE TITLE
Could not find any Roku devices after 10 seconds

### ISSUE THREAD

**Issue by gradyhouston** [bschlenk/homebridge-roku#192]
I have my Roku on a separate VLAN than my private network. I have my homebridge setup on a RPi on that private network but have firewall rules to allow the private network to talk to the "IoT" network (that's where the Roku is). When I run `homebridge-roku-config --merge`, I get:

`Error: Could not find any Roku devices after 10 seconds
    at RokuFinder.<anonymous> (/usr/lib/node_modules/homebridge-roku/node_modules/roku-client/dist/discover.js:96:20)
    at RokuFinder.emit (events.js:315:20)
    at Timeout.done (/usr/lib/node_modules/homebridge-roku/node_modules/roku-client/dist/discover.js:62:19)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)`

I can access other IoT devices with them being on the other VLAN, so I know it works. Is there a way to specifically assign an IP for the config to look for using `homebridge-roku-config --merge`? I can't generate a config because this command never finds my Roku.

**Comment by leftytennis** [comment]
I'm having the same issue, did you ever find a workaround?

**Comment by jerrywaller** [comment]
Also running into this issue.
