### ISSUE TITLE
Error running homebridge-roku-config

### ISSUE THREAD

**Issue by ksolomon** [bschlenk/homebridge-roku#2]
I get the following error when trying to run the config step.  Any guidance on how to complete the setup?

pi@Homebridge: /opt/node/lib/node_modules/homebridge-roku/bin $ ./homebridge-roku-config 
/opt/node/lib/node_modules/homebridge-roku/node_modules/nodeku/lib/discovery.js:43
      if (Boolean(~headers.SERVER.search(/Roku/)) && ipAddress) {
                                 ^

TypeError: Cannot read property 'search' of undefined
    at SsdpClient.client.on.headers (/opt/node/lib/node_modules/homebridge-roku/node_modules/nodeku/lib/discovery.js:43:34)
    at emitThree (events.js:116:13)
    at SsdpClient.emit (events.js:194:7)
    at SsdpClient.parseResponse [as _parseResponse] (/opt/node/lib/node_modules/homebridge-roku/node_modules/node-ssdp/lib/index.js:432:8)
    at SsdpClient.SSDP._parseMessage (/opt/node/lib/node_modules/homebridge-roku/node_modules/node-ssdp/lib/index.js:275:10)
    at Socket.onSocketMessage (/opt/node/lib/node_modules/homebridge-roku/node_modules/node-ssdp/lib/index.js:231:12)
    at emitTwo (events.js:106:13)
    at Socket.emit (events.js:191:7)
    at UDP.onMessage (dgram.js:550:8)
pi@Homebridge: /opt/node/lib/node_modules/homebridge-roku/bin $

**Comment by bschlenk** [comment]
It has been a while since I've worked on this project. It looks like nodeku has been updated to 1.0.10, which may have introduced a breaking change. 

I can look into it, but this project doesn't do much. I'm thinking about writing an Alexa skill instead, as there's much more freedom in what you can ask Alexa over Siri.

**Comment by bschlenk** [comment]
This works on my network with nodeku@1.0.10. You can debug this by modifying node_modules/nodeku/lib/discovery.js, and somewhere within the callback on [line 35](https://github.com/sgnl/nodeku/blob/master/lib/discovery.js#L35) add a console.log(headers). Then run bin/homebridge-roku-config again and see all the headers it outputs.

There must be a device on your network that is responding without a SERVER header. You'll have to raise this as an issue on [nodeku](https://github.com/sgnl/nodeku), since that package handles the discovery of the available roku devices.

**Comment by ksolomon** [comment]
Thanks for looking into it.  I'll see what I can dig up, and at worst, raise an issue with nodeku.
