### ISSUE TITLE
Issues with roku config

### ISSUE THREAD

**Issue by roberkane212** [bschlenk/homebridge-roku#20]
I’m fairly new to this. I have gotten Homebridge installed and looked up the plugin. However I’m getting a command not found for the whole thing. Not sure what I’m doing wrong

**Comment by bschlenk** [comment]
Can you elaborate on the issue you are facing? Provide the steps you took to get to where you are now and the error you are seeing.

**Comment by roberkane212** [comment]
I install node then installed Homebridge in terminal. Then opened Homebridge in terminal inserted code in home app. And saw Homebridge in the app. Everything was working fine, tried to set up my roku tv in the json file, now i can't get home bridge to open at all

Admin$ homebridge
/usr/local/lib/node_modules/homebridge/lib/server.js:219
var username = config.bridge.username;
^

TypeError: Cannot read property 'username' of undefined
at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:219:31)
at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:56:38)
at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:30:16)
at Object. (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.runMain (module.js:604:10)

is the error message i get,

**Comment by roberkane212** [comment]
Is there anyone who can help??

**Comment by roberkane212** [comment]
Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/homebridge/package.json'
    at Object.openSync (fs.js:436:3)
    at Object.readFileSync (fs.js:341:35)
    at getVersion (/usr/local/lib/node_modules/homebridge/lib/version.js:10:35)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/version.js:6:18)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)

is what I'm getting now

**Comment by bschlenk** [comment]
Can you post the contents of your `~/.homebridge/config.json` file? It sounds like a section might be missing. 

The second issue sounds like an installation problem. You might want to try uninstalling and reinstalling Homebridge.

**Comment by roberkane212** [comment]
I uninstalled, now won’t install anymore. I’ve put the json back to the sample version. Can do anything. Now when I try to uninstall let’s me I don’t have permission

**Comment by roberkane212** [comment]
I’m doing this all on my Mac by the way
