### ISSUE TITLE
Error: Could not find any Roku devices after 10 seconds

### ISSUE THREAD

**Issue by Jacksonbm1** [bschlenk/homebridge-roku#246]
Here's what happened:

Install:

```
pi@raspberrypi:~ $ npm install -g homebridge-roku@latest
/home/pi/.nvm/versions/node/v14.17.1/bin/homebridge-roku-config -> /home/pi/.nvm/versions/node/v14.17.1/lib/node_modules/homebridge-roku/bin/setup
+ homebridge-roku@3.0.2
updated 1 package in 3.763s
```

Roku is on

`/home/pi/.nvm/versions/node/v14.17.1/bin/homebridge-roku-config`

-->
```
Error: Could not find any Roku devices after 10 seconds
    at RokuFinder.<anonymous> (/home/pi/.nvm/versions/node/v14.17.1/lib/node_modules/homebridge-roku/node_modules/roku-client/dist/discover.js:96:20)
    at RokuFinder.emit (events.js:375:28)
    at Timeout.done (/home/pi/.nvm/versions/node/v14.17.1/lib/node_modules/homebridge-roku/node_modules/roku-client/dist/discover.js:62:19)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
```

Any idea how to fix it?

**Comment by hazelement** [comment]
In my case, it was my firewall. I disabled it on my server and run the config command. After I'm all done, I just re-enabled the firewall.
