### ISSUE TITLE
Error with homebrigde-roku-config

### ISSUE THREAD

**Issue by IamChrisHeX** [bschlenk/homebridge-roku#7]
When trying to config I get this error:

I'm running this on a windows 7 box with node 8.9.4

path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:499:7)
    at Object.<anonymous> (C:\Users\HeX\AppData\Roaming\npm\node_modules\homebri
dge-roku\src\setup.js:8:32)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\HeX\AppData\Roaming\npm\node_modules\homebri
dge-roku\bin\setup:5:70)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)

**Comment by bschlenk** [comment]
It looks like I've assumed a unix directory structure here: https://github.com/bschlenk/homebridge-roku/blob/master/src/setup.js#L8
I haven't tested this on a windows machine, do you know where homebridge looks for the config.json file on windows?

**Comment by IamChrisHeX** [comment]
%homepath%/.homebridge/config.json

**Comment by IamChrisHeX** [comment]
Sent a pull request

**Comment by bschlenk** [comment]
Published version 2.0.1
